// EXERCISE 1

/*
Practice.
Error handling mechanism to catch runtime errors using try-catch-finally block
*/

try {
    // code thta may throw an error
} catch (err) {
    // code to be excuted if an error occurs
} finally {
    // code to be excuted rgardless of an error occurs or not
}


/*
try-catch-finally
*/

// try: wrap suspious code that may throw an error in try block. 

/*
 catch: write code to do something in catch block when an error occurs.
the catch can have a parameters that will give an error information 
*/

// finally: finally block will always be executed regardless of the occurrence of an error
